---
- name: enable nginx
  systemd:
    name: nginx
    enabled: true

- name: start nginx
  systemd:
    name: nginx
    state: started

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted