---
# Add tasks to update and upgrade the system here
# Add tasks to install packages such as python3 and nginx here
# Use a defaults/main.yml file to define package names and/or versions if necessary
# Use a handlers/main.yml file to enable and start nginx

- name: Update and upgrade the system
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
  become: true
  # Do this to avoid the error ansible-playbook playbooks/main.yml --ask-become-pass

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Install Python3
  apt:
    name: python3
    state: present

- name: Install Nginx
  apt:
    name: nginx
    state: present
  notify:
    - enable nginx
    - start nginx
